package host

var (
	sudoersTemplate = `#
# THIS FILE IS AUTOGENERATED
# Generated at  {{ .GenTime }} by Commander
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
{{ range .Sudoers }}
{{ . }} ALL=(ALL:ALL) ALL
{{ end }}

# Group privilege specification
# %groupname ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

# includedir /etc/sudoers.d
`
)
