package ssh

var (
	templateStr = `#
# THIS FILE IS AUTOGENERATED. MODIFICATiONS WiLL NOT BE PERSISTENT.
# Generated at  {{ .GenTime }} by Commander
#
# See the sshd_config(5) manpage for details

# What ports, IPs and protocols we listen for
Port 22

# Use these options to restrict which interfaces/protocols sshd will bind to
ListenAddress ::
ListenAddress 0.0.0.0

# SSHv2
Protocol 2

# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Privilege Separation is turned on for security
UsePrivilegeSeparation yes

# Lifetime and size of ephemeral version 1 server key
KeyRegenerationInterval 3600
ServerKeyBits 1024

# Logging
SyslogFacility AUTH
LogLevel INFO

# Login config
LoginGraceTime 120
PermitRootLogin no
StrictModes yes

# Authentication methods
PasswordAuthentication {{ .AllowPasswordAuth }}
PubkeyAuthentication {{ .AllowPubkeyAuth }}
ChallengeResponseAuthentication no
HostbasedAuthentication no
RhostsRSAAuthentication no

# Users authorized keys
AuthorizedKeysFile	%h/.ssh/authorized_keys

# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

# To enable empty passwords, change to yes (NOT RECOMMENDED)
PermitEmptyPasswords no

# Print messages on login
PrintMotd no
PrintLastLog yes

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# DEFAULTS
#
# These settings are intentionally unconfigured/commented out.
# The sshd daemon will pick up sane values (as shown) for these.
#

# Keepalives to detect remote host crashes
#TCPKeepAlive yes

# Kerberos options
#KerberosAuthentication no
#KerberosGetAFSToken no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

# X11 Forwarding
#X11Forwarding yes
#X11DisplayOffset 10

# Whether to use 'login' for interactive login
#UseLogin no

# Control num/rate of unauthenticated sessions
#MaxStartups 10:30:60

# This file is sent to the user *before* auth is performed
#Banner /etc/issue.net

# Allow client to pass locale environment variables
#AcceptEnv LANG LC_*

# SFTP
#Subsystem sftp /usr/lib/openssh/sftp-server

# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
#IgnoreUserKnownHosts yes
`
)
